#!/bin/bash
echo "Введите id:"
read minimum
echo "Введите value:"
read maximum

idf()
{
for (( k=1; k <=minimum; k++ )) 
do
valuef
echo "$k, $(date +%s%N), $((( $RANDOM % 9 + 1 )*10))" >> file.txt
done
}

valuef()
{
for (( l=1; l <maximum; l++ ))  
do
echo "$k, $(date +%s%N), $((( $RANDOM % 9 + 1 )*10))" >> file.txt 
done
}

idf
