version: '3.7'
services:
  nginx:
    image: akemi48/nginx:1.5
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
    links:
      - web
  web:
    image: akemi48/tet:1.66
    ports:
      - "5000:5000"
    links:
      - db
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
